import { Component, OnInit, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-componente-datos-ejemplo',
  templateUrl: './componente-datos-ejemplo.component.html',
  styleUrls: ['./componente-datos-ejemplo.component.css']
})
export class ComponenteDatosEjemploComponent implements OnInit {
  citas: any[] = []; 
  usuariosPaciente: any[] = []; 

  @Output() citasEmitter: EventEmitter<any[]> = new EventEmitter<any[]>();
  @Output() usuariosPacienteEmitter: EventEmitter<any[]> = new EventEmitter<any[]>();

  ngOnInit() {
    this.citas = [
      { 
        id: 1,
        nombre: 'Juan',
        primerApellido: 'Pérez',
        segundoApellido: 'González',
        fecha: '2024-01-20',
        hora: '10:00 AM',
        medicoAsignado: 'Dr. García',
        servicio: 'Radiología'
      },
      { 
        id: 2,
        nombre: 'Ana',
        primerApellido: 'Gómez',
        segundoApellido: 'López',
        fecha: '2024-01-21',
        hora: '11:30 AM',
        medicoAsignado: 'Dra. Martínez',
        servicio: 'Cita Normal'
      },
      { 
        id: 3,
        nombre: 'Carlos',
        primerApellido: 'Ruiz',
        segundoApellido: 'Fernández',
        fecha: '2024-01-22',
        hora: '02:15 PM',
        medicoAsignado: 'Dr. Rodríguez',
        servicio: 'Radiología'
      },
      { 
        id: 4,
        nombre: 'María',
        primerApellido: 'Hernández',
        segundoApellido: 'Gómez',
        fecha: '2024-01-23',
        hora: '03:45 PM',
        medicoAsignado: 'Dra. López',
        servicio: 'Cita Normal'
      },

      { 
        id: 5,
        nombre: 'Pedro',
        primerApellido: 'Ramírez',
        segundoApellido: 'Fernández',
        fecha: '2024-01-24',
        hora: '08:30 AM',
        medicoAsignado: 'Dr. Sánchez',
        servicio: 'Radiología'
      },

      { 
        id: 6,
        nombre: 'Laura',
        primerApellido: 'Gutiérrez',
        segundoApellido: 'López',
        fecha: '2024-01-25',
        hora: '09:45 AM',
        medicoAsignado: 'Dra. Hernández',
        servicio: 'Cita Normal'
      },
      { 
        id: 7,
        nombre: 'Roberto',
        primerApellido: 'Fernández',
        segundoApellido: 'Martínez',
        fecha: '2024-01-26',
        hora: '01:00 PM',
        medicoAsignado: 'Dr. Pérez',
        servicio: 'Radiología'
      },
      { 
        id: 8,
        nombre: 'Isabel',
        primerApellido: 'Gómez',
        segundoApellido: 'Sánchez',
        fecha: '2024-01-27',
        hora: '03:30 PM',
        medicoAsignado: 'Dra. Ramírez',
        servicio: 'Cita Normal'
      },
      { 
        id: 9,
        nombre: 'Javier',
        primerApellido: 'Martínez',
        segundoApellido: 'Rodríguez',
        fecha: '2024-01-28',
        hora: '04:45 PM',
        medicoAsignado: 'Dr. López',
        servicio: 'Radiología'
      },
      { 
        id: 10,
        nombre: 'Lorena',
        primerApellido: 'Hernández',
        segundoApellido: 'González',
        fecha: '2024-01-29',
        hora: '10:00 AM',
        medicoAsignado: 'Dra. González',
        servicio: 'Cita Normal'
      },
      { 
        id: 11,
        nombre: 'Alberto',
        primerApellido: 'Sánchez',
        segundoApellido: 'Fernández',
        fecha: '2024-01-30',
        hora: '02:15 PM',
        medicoAsignado: 'Dr. Rodríguez',
        servicio: 'Radiología'
      },
      { 
        id: 12,
        nombre: 'Sofía',
        primerApellido: 'Fernández',
        segundoApellido: 'López',
        fecha: '2024-02-01',
        hora: '03:45 PM',
        medicoAsignado: 'Dra. López',
        servicio: 'Cita Normal'
      },
      { 
        id: 13,
        nombre: 'Francisco',
        primerApellido: 'López',
        segundoApellido: 'Gómez',
        fecha: '2024-02-02',
        hora: '08:30 AM',
        medicoAsignado: 'Dr. Sánchez',
        servicio: 'Radiología'
      },
      { 
        id: 14,
        nombre: 'Elena',
        primerApellido: 'Gómez',
        segundoApellido: 'Martínez',
        fecha: '2024-02-03',
        hora: '09:45 AM',
        medicoAsignado: 'Dra. Hernández',
        servicio: 'Cita Normal'
      },
      
      
    ];

    this.usuariosPaciente = [
      { 
        nip: '12345678A',
        nombre: 'Elena',
        primerApellido: 'Gómez',
        segundoApellido: 'Martínez',
        fechaNacimiento: '1990-05-15',
        telefono: '600123456',
        dni: '12345678Z',
        sexo: 'Femenino',
        provincia: 'Madrid',
        codigoPostal: '28001',
        numero: '123',
        puerta: '2B',
        poblacion: 'Madrid',
        direccion: 'Calle Principal',
        piso: '2',
        escalera: 'A',
      },
      { 
        nip: '87654321B',
        nombre: 'Juan',
        primerApellido: 'Pérez',
        segundoApellido: 'González',
        fechaNacimiento: '1985-08-20',
        telefono: '601987654',
        dni: '87654321X',
        sexo: 'Masculino',
        provincia: 'Barcelona',
        codigoPostal: '08002',
        numero: '456',
        puerta: '1A',
        poblacion: 'Barcelona',
        direccion: 'Avenida Central',
        piso: '3',
        escalera: 'B',
      },

      { 
        nip: '98765432C',
        nombre: 'Laura',
        primerApellido: 'Fernández',
        segundoApellido: 'Gómez',
        fechaNacimiento: '1988-12-10',
        telefono: '602345678',
        dni: '98765432Y',
        sexo: 'Femenino',
        provincia: 'Valencia',
        codigoPostal: '46001',
        numero: '789',
        puerta: '3C',
        poblacion: 'Valencia',
        direccion: 'Calle Valencia',
        piso: '4',
        escalera: 'C',
      },
      { 
        nip: '23456789D',
        nombre: 'Carlos',
        primerApellido: 'Rodríguez',
        segundoApellido: 'López',
        fechaNacimiento: '1995-06-25',
        telefono: '603456789',
        dni: '23456789M',
        sexo: 'Masculino',
        provincia: 'Sevilla',
        codigoPostal: '41001',
        numero: '234',
        puerta: '2B',
        poblacion: 'Sevilla',
        direccion: 'Avenida Sevilla',
        piso: '1',
        escalera: 'B',
      },
      { 
        nip: '34567890E',
        nombre: 'Ana',
        primerApellido: 'Martínez',
        segundoApellido: 'Sánchez',
        fechaNacimiento: '1992-09-15',
        telefono: '604567890',
        dni: '34567890N',
        sexo: 'Femenino',
        provincia: 'Alicante',
        codigoPostal: '03001',
        numero: '567',
        puerta: '1A',
        poblacion: 'Alicante',
        direccion: 'Calle Alicante',
        piso: '2',
        escalera: 'A',
      },
      { 
        nip: '45678901F',
        nombre: 'Francisco',
        primerApellido: 'López',
        segundoApellido: 'Hernández',
        fechaNacimiento: '1980-04-05',
        telefono: '605678901',
        dni: '45678901J',
        sexo: 'Masculino',
        provincia: 'Málaga',
        codigoPostal: '29001',
        numero: '890',
        puerta: '4D',
        poblacion: 'Málaga',
        direccion: 'Calle Málaga',
        piso: '3',
        escalera: 'D',
      },
      { 
        nip: '56789012G',
        nombre: 'Sofía',
        primerApellido: 'Gutiérrez',
        segundoApellido: 'Ruiz',
        fechaNacimiento: '1987-11-20',
        telefono: '606789012',
        dni: '56789012K',
        sexo: 'Femenino',
        provincia: 'Murcia',
        codigoPostal: '30001',
        numero: '123',
        puerta: '1C',
        poblacion: 'Murcia',
        direccion: 'Calle Murcia',
        piso: '4',
        escalera: 'C',
      },
      { 
        nip: '67890123H',
        nombre: 'Javier',
        primerApellido: 'Sánchez',
        segundoApellido: 'Fernández',
        fechaNacimiento: '1993-02-15',
        telefono: '607890123',
        dni: '67890123L',
        sexo: 'Masculino',
        provincia: 'Zaragoza',
        codigoPostal: '50001',
        numero: '456',
        puerta: '3B',
        poblacion: 'Zaragoza',
        direccion: 'Avenida Zaragoza',
        piso: '2',
        escalera: 'B',
      },
      { 
        nip: '78901234I',
        nombre: 'Elena',
        primerApellido: 'Fernández',
        segundoApellido: 'Gómez',
        fechaNacimiento: '1990-07-12',
        telefono: '608901234',
        dni: '78901234O',
        sexo: 'Femenino',
        provincia: 'Bilbao',
        codigoPostal: '48001',
        numero: '789',
        puerta: '2A',
        poblacion: 'Bilbao',
        direccion: 'Calle Bilbao',
        piso: '1',
        escalera: 'A',
      },
      { 
        nip: '89012345J',
        nombre: 'Daniel',
        primerApellido: 'Martínez',
        segundoApellido: 'López',
        fechaNacimiento: '1986-06-30',
        telefono: '609012345',
        dni: '89012345P',
        sexo: 'Masculino',
        provincia: 'Palma de Mallorca',
        codigoPostal: '07001',
        numero: '234',
        puerta: '3D',
        poblacion: 'Palma de Mallorca',
        direccion: 'Calle Mallorca',
        piso: '4',
        escalera: 'D',
      },
      { 
        nip: '90123456K',
        nombre: 'María',
        primerApellido: 'López',
        segundoApellido: 'Hernández',
        fechaNacimiento: '1984-05-18',
        telefono: '610123456',
        dni: '90123456Q',
        sexo: 'Femenino',
        provincia: 'Las Palmas',
        codigoPostal: '35001',
        numero: '567',
        puerta: '1B',
        poblacion: 'Las Palmas',
        direccion: 'Avenida Las Palmas',
        piso: '2',
        escalera: 'B',
      },
      { 
        nip: '01234567L',
        nombre: 'Andrés',
        primerApellido: 'Sánchez',
        segundoApellido: 'Fernández',
        fechaNacimiento: '1991-09-22',
        telefono: '611234567',
        dni: '01234567R',
        sexo: 'Masculino',
        provincia: 'A Coruña',
        codigoPostal: '15001',
        numero: '890',
        puerta: '4C',
        poblacion: 'A Coruña',
        direccion: 'Calle A Coruña',
        piso: '3',
        escalera: 'C',
      },
      { 
        nip: '12345678A',
        nombre: 'Luis',
        primerApellido: 'García',
        segundoApellido: 'Martínez',
        fechaNacimiento: '1993-04-12',
        telefono: '612345678',
        dni: '12345678Z',
        sexo: 'Masculino',
        provincia: 'Valencia',
        codigoPostal: '46002',
        numero: '567',
        puerta: '1A',
        poblacion: 'Valencia',
        direccion: 'Calle Valencia',
        piso: '2',
        escalera: 'B',
      },
      { 
        nip: '87654321B',
        nombre: 'Sara',
        primerApellido: 'Rodríguez',
        segundoApellido: 'López',
        fechaNacimiento: '1988-11-05',
        telefono: '613456789',
        dni: '87654321X',
        sexo: 'Femenino',
        provincia: 'Barcelona',
        codigoPostal: '08003',
        numero: '890',
        puerta: '3B',
        poblacion: 'Barcelona',
        direccion: 'Avenida Central',
        piso: '1',
        escalera: 'C',
      },
      { 
        nip: '23456789C',
        nombre: 'Jorge',
        primerApellido: 'Fernández',
        segundoApellido: 'Sánchez',
        fechaNacimiento: '1985-08-20',
        telefono: '614567890',
        dni: '23456789M',
        sexo: 'Masculino',
        provincia: 'Alicante',
        codigoPostal: '03002',
        numero: '123',
        puerta: '2C',
        poblacion: 'Alicante',
        direccion: 'Calle Alicante',
        piso: '3',
        escalera: 'A',
      },
      { 
        nip: '34567890D',
        nombre: 'Laura',
        primerApellido: 'Martínez',
        segundoApellido: 'Gómez',
        fechaNacimiento: '1990-12-18',
        telefono: '615678901',
        dni: '34567890N',
        sexo: 'Femenino',
        provincia: 'Málaga',
        codigoPostal: '29002',
        numero: '456',
        puerta: '4D',
        poblacion: 'Málaga',
        direccion: 'Calle Málaga',
        piso: '4',
        escalera: 'D',
      },
      { 
        nip: '45678901E',
        nombre: 'Carlos',
        primerApellido: 'Gutiérrez',
        segundoApellido: 'Ruiz',
        fechaNacimiento: '1987-07-30',
        telefono: '616789012',
        dni: '45678901J',
        sexo: 'Masculino',
        provincia: 'Murcia',
        codigoPostal: '30002',
        numero: '789',
        puerta: '1B',
        poblacion: 'Murcia',
        direccion: 'Calle Murcia',
        piso: '2',
        escalera: 'B',
      },
      { 
        nip: '56789012F',
        nombre: 'Elena',
        primerApellido: 'Sánchez',
        segundoApellido: 'Fernández',
        fechaNacimiento: '1984-05-18',
        telefono: '617890123',
        dni: '56789012K',
        sexo: 'Femenino',
        provincia: 'Zaragoza',
        codigoPostal: '50002',
        numero: '234',
        puerta: '3C',
        poblacion: 'Zaragoza',
        direccion: 'Avenida Zaragoza',
        piso: '1',
        escalera: 'C',
      },
      { 
        nip: '67890123G',
        nombre: 'Miguel',
        primerApellido: 'López',
        segundoApellido: 'Hernández',
        fechaNacimiento: '1992-09-22',
        telefono: '618901234',
        dni: '67890123L',
        sexo: 'Masculino',
        provincia: 'Bilbao',
        codigoPostal: '48002',
        numero: '567',
        puerta: '4A',
        poblacion: 'Bilbao',
        direccion: 'Calle Bilbao',
        piso: '3',
        escalera: 'D',
      },
      { 
        nip: '78901234H',
        nombre: 'Lucía',
        primerApellido: 'Martínez',
        segundoApellido: 'López',
        fechaNacimiento: '1991-06-30',
        telefono: '619012345',
        dni: '78901234O',
        sexo: 'Femenino',
        provincia: 'Palma de Mallorca',
        codigoPostal: '07002',
        numero: '890',
        puerta: '2A',
        poblacion: 'Palma de Mallorca',
        direccion: 'Calle Mallorca',
        piso: '4',
        escalera: 'A',
      },
      { 
        nip: '89012345I',
        nombre: 'Alejandro',
        primerApellido: 'Gómez',
        segundoApellido: 'Martínez',
        fechaNacimiento: '1986-04-15',
        telefono: '620123456',
        dni: '89012345P',
        sexo: 'Masculino',
        provincia: 'Las Palmas',
        codigoPostal: '35002',
        numero: '123',
        puerta: '1C',
        poblacion: 'Las Palmas',
        direccion: 'Avenida Las Palmas',
        piso: '2',
        escalera: 'A',
      },
      { 
        nip: '01234567J',
        nombre: 'Sandra',
        primerApellido: 'Sánchez',
        segundoApellido: 'Fernández',
        fechaNacimiento: '1989-11-12',
        telefono: '621234567',
        dni: '01234567R',
        sexo: 'Femenino',
        provincia: 'A Coruña',
        codigoPostal: '15002',
        numero: '456',
        puerta: '3B',
        poblacion: 'A Coruña',
        direccion: 'Calle A Coruña',
        piso: '1',
        escalera: 'B',
      },
    ];
    
    this.citasEmitter.emit(this.citas);
    this.usuariosPacienteEmitter.emit(this.usuariosPaciente);


  }
}
